### ISSUE TITLE
[ENH] Java 17

### ISSUE THREAD

**Issue by AlexanderNeumann** [rwth-acis/las2peer#100]
1. **Motivation** - Currently we are using Java 14. In the next months Java 17 will be released which is the next LTS version. 
2. **Specification** - Replace Java 14 with Java 17 when it is possible. 
3. **Finalised state** - Freepastry and las2peer should run without any errors or deprecation warnings with Java 17

**Comment by phil-cd** [comment]
The current las2peer version (v1.1.2) uses Gradle 6.8. We may need to use a later version of Gradle to build with Java 17. (https://docs.gradle.org/current/userguide/compatibility.html)
