### ISSUE TITLE
[ENH] Decrease the log level for logs from the blockchain to FINE

### ISSUE THREAD

**Issue by lakhoune** [rwth-acis/las2peer#101]
1. **Motivation** - The blockchain observer tends to  spam the logs a lot. This hinders debugging services and most messages just cannot be looked up which hinders debugging of services
2. **Specification** - If those messages are only logged on FINE then services can set ` L2pLogger.setGlobalConsoleLevel(Level.INFO);` and still see the message info logs

**Comment by erdzan12** [comment]
Branch [issue-101-decrease-log-level ](https://github.com/rwth-acis/las2peer/tree/issue-101-decrease-log-level) addresses this issue, by decreasing the log level to fine for the ChainObserver for transactions.
