### ISSUE TITLE
[BUG] las2peer generates a new user agent after each login

### ISSUE THREAD

**Issue by AlexanderNeumann** [rwth-acis/las2peer#126]
1. **Summary** - Whenever I log in I get a new user agent.
2. **Bug Details** - A detailed explanation of the issue, structured in subsections:
   1. **What?** - I cannot access encrypted data, because my agent is not valid. 
   2. **Where?** - E.g. Noracle. 
   3. **When?/How often?** - Every time I log in. 
   4. **How?/Current state** - Log into a las2peer service, visit e.g. https://git.tech4comp.dbis.rwth-aachen.de/las2peer/currentagent to check your current agent. Reset your session (or use a private browser session) and log in again and recheck your agent.

**Comment by Siminho** [comment]
fyi
When starting a local las2peer network, for example with the Distributed Noracle Services, the problem does not occur. So maybe it is only related to the las2peer developer network (las2peer-bootstrap.sbf-dev)?

**Comment by lakhoune** [comment]
When I visit  https://git.tech4comp.dbis.rwth-aachen.de/las2peer/currentagent, I get the following error:
```
This page contains the following errors:
error on line 1 at column 33: Namespace prefix las2peer on agent is not defined
Below is a rendering of the page up to the first error.
```
Furthermore, I cannot login on https://git.tech4comp.dbis.rwth-aachen.de/las2peer/webapp/welcome , as I get the

**Comment by Siminho** [comment]
Can you update the repository with the las2peer version of 1.2.1? Then I can test, if this solves the problem.

**Comment by lakhoune** [comment]
We updated las2peer on the dev network. It seems like this problem still persists

**Comment by lakhoune** [comment]
For my test account, I received the same agent when I called https://git.tech4comp.dbis.rwth-aachen.de/las2peer/currentagent

**Comment by Aran30** [comment]
One thing to note, the dev network node is not an eth node, yet for some reason, a "eth node" null pointer exception comes up when trying to export agents based on their login names: 

```
Internal Server Error: Cannot invoke "i5.las2peer.p2p.EthereumNode.getRegistryClient()" because "this.ethereumNode" is null
java.lang.NullPointerException: Cannot invoke "i5.las2peer.p2p.EthereumNode.getRegistryClient()" because "this.ethereumNode" is null
```

**Comment by Aran30** [comment]
Turns out the problem stemmed from weirdly configured access rights to the persistent storage. It now works again.
