### ISSUE TITLE
[BUG] *_token headers being stripped

### ISSUE THREAD

**Issue by BorisJov** [rwth-acis/las2peer#143]
1. **Summary** - Any header with "token" in its name gets stripped from HTTP headers intended for las2peer services.
2. **Bug Details** 
   1. **What?** - Not sure if this is a bug or intended, but authorisation headers are being removed from HTTP requests intended for las2peer services. This prevents, for example, a l2p service using OIDC tokens if they want to pass it through one of these headers. You have to use a custom header if you want to implement it.
   2. **Where?** - I would guess somewhere in las2peer core. Whichever part handles request routing and authentication.
   3. **When?/How often?** - With every HTTP request to a las2peer service running in the cluster.
   4. **How?/Current state** - When you send a HTTP request with e.g. "access_token", "some_token", "x_token"... headers, they just get removed and the final service can no longer retrieve them from the context.

**Comment by lakhoune** [comment]
Seems like the underscore character is causing the issue on Kubernetes: 

https://stackoverflow.com/questions/22856136/why-do-http-servers-forbid-underscores-in-http-header-names
