### ISSUE TITLE
Update Java 14

### ISSUE THREAD

**Issue by klamma** [rwth-acis/las2peer#64]
freepastry and las2peer should compile with Java 14

**Comment by phil-cd** [comment]
The PR for updating FreePastry to Java 14 can be found [here](https://github.com/rwth-acis/FreePastry/pull/1).
There's also a new [FreePastry release](https://github.com/rwth-acis/FreePastry/releases/tag/v3.0.0), which is going to be used in Java 14 versions of las2peer.
