### ISSUE TITLE
[ENH] Illegal reflective access operation Warning (Java Problem)

### ISSUE THREAD

**Issue by Aran30** [rwth-acis/las2peer#82]
After upgrading las2peer's java version to 14, some new warnings popped up about "illegal reflective access operations" being made. These currently pop up 3 times during the build process of the las2peer-bundle and are caused by following classes:  

- org.apache.ivy.util.url.IvyAuthenticator (https://issues.apache.org/jira/browse/IVY-1569)
- org.mockito.cglib.core.ReflectUtils$2
- rice.p2p.util.XMLObjectOutputStream (This access being caused by the latest FreePastry change to be Java 14 compatible [316ce5c](https://github.com/rwth-acis/FreePastry/commit/316ce5c89bf5f71a7a9633b868aaa8425a3448e0))

Note that when starting a service, the warning caused by the FreePastry change will also pop up. 
The warnings look like the following: 

```
    [junit] WARNING: An illegal reflective access operation has occurred
    [junit] WARNING: Illegal reflective access by rice.p2p.util.XMLObjectOutputStream (file:/home/jenkins/.jenkins/workspace/las2peer%20Core/core/lib/FreePastry-3.0.0.jar) to field java.lang.Number.serialVersionUID
    [junit] WARNING: Please consider reporting this to the maintainers of rice.p2p.util.XMLObjectOutputStream
    [junit] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    [junit] WARNING: All illegal access operations will be denied in a future release
```
The problem itself stems from Java 9's introduction of modules. More useful information concerning this warning can be found here:
- https://stackoverflow.com/questions/50251798/what-is-an-illegal-reflective-access

Currently, these warnings do not break anything, but as mentioned in the warning, the illegal access may be denied in a future java version. Thus, something to keep in mind for a future upgrade of las2peer's java version.

**Comment by phil-cd** [comment]
> Currently, these warnings do not break anything, but as mentioned in the warning, the illegal access may be denied in a future java version. Thus, something to keep in mind for a future upgrade of las2peer's java version.

This now happened with Java 17 (see https://openjdk.java.net/jeps/403). For FreePastry to be working, at least the packages java.lang and java.util need to be open. We could use the Add-Opens manifest attribute for this (as described here https://openjdk.java.net/jeps/261#Packaging:-Modular-JAR-files).

Here is the corresponding change in las2peer: https://github.com/rwth-acis/las2peer/commit/787d57afc7cab4132695e117ce7af20b54335959
