### ISSUE TITLE
[BUG] Agent not found in registry

### ISSUE THREAD

**Issue by AlexanderNeumann** [rwth-acis/las2peer#91]
1. **Summary** - When I try to login I get a 401 error, because my agent is not found in the ethereum blockchain
2. **Bug Details** - A detailed explanation of the issue, structured in subsections:
   1. **What?** - data in blockchain does not match agent stored in shared storage!
   2. **Where?** - las2peer core/Ethereum Agent
   3. **When?/How often?** - Error occurs when the Agent is found in the shared storage but not in the ethereum blockchain
   4. **How?/Current state** - Well, I honestly don't know how that happened. If you have an existing agent and you would upgrade it to an ethereum agent shouldn't it be stored in the chain? Or should be there some import functionality of ethereum agents? 
3. *(Optional)* **Fixed state** - Create missing entry in the chain?  
https://github.com/rwth-acis/las2peer/blob/master/core/src/main/java/i5/las2peer/p2p/EthereumNode.java#L279

las2peer log: 
```
OIDC sub found. Authenticating...
attempting login with id: OIDC_SUB-.... I removed my id :) 
User not found in registry
AgentException when trying to auth agent: User data in blockchain does not match agent stored in shared storage!
```

**Comment by erdzan12** [comment]
I tried to reproduce the bug but did not have success, I tried to let the eth bootsraped node run for some days with other test services bootstraped to it, but with no success again.

The weird thing is: 
[https://github.com/rwth-acis/las2peer/blob/master/core/src/main/java/i5/las2peer/p2p/EthereumNode.java#L279](url)
 The mentioned code only gets called, when the agent  retrieved from the node storage is an ethereumAgent, but this implies that upon it's creation the agent so the user must also have been registered in the blockchain, if there did not happen any errors during the storage in the blockchain. Here: [https://github.com/rwth-acis/las2peer/blob/master/core/src/main/java/i5/las2peer/p2p/EthereumNode.java#L170](url)

A possible fix would be the already stated solution to register the agent/user after it has been fetched from the node storage as an ethereumAgent and, when it is not present in the bc, but this may only get rid of the symptoms but not the real cause?

**Comment by AlexanderNeumann** [comment]
> A possible fix would be the already stated solution to register the agent/user after it has been fetched from the node storage as an ethereumAgent and, when it is not present in the bc, but this may only get rid of the symptoms but not the real cause?

That's true, I hope no one has deleted the blockchain data! But if that happened, the system should be able to restore itself. In the state it is now, it is unusable.

**Comment by Aran30** [comment]
Further information after inspecting the logs and trying to log in with different agents:
When using my account (Aaron30), the blockchain data returns 0x00 when trying to fetch my account from the blockchain.
So (L216)[https://github.com/rwth-acis/las2peer/blob/9fcd2733b0396debd7d28da06932a553f2a10ea8/core/src/main/java/i5/las2peer/registry/ReadOnlyRegistryClient.java#L216] returns true in my case. 

Using @erdzan12 's account, the same line returns false (meaning erdzan's data was correctly fetched), but the agent id & pubkey found in the node storage is not identical to the ones in the blockchain, thus failing to log in. 

Finally, using @lakhoune 's account, the login worked.

Interestingly enough, after checking manually, my agent is indeed stored in the blockchain. 

What's also interesting, is the fact that when starting the bootstrap node, some "observed user registration" logs come up, containing what seems to be las2peer agents that are stored in the blockchain. Yet, there are only a few there (My agent is not mentioned).

**Comment by erdzan12** [comment]
After looking at the logs it was noticed that for some reason the bootstrap node has deployed the smart contracts during a boot again, where this happens only, when the las2peer bootstrap cannot find the migration.log file which has been created from thee first start and deployment of the smart contracts. 
Therefore, a new migration.log file was generated with new addresses for the contracts and therefore users could not be found in the registry. After replacing the address for the userregistry contract in the migration.log file, the login worked again the users we tested it for @Aran30 and me. But for some reason, for users where the login worked before we replaced the address in the migration.log, are not able to login now, which could be interpreted like this: where the user in the node storage do not correspond to the users in the original userregistry saved under the address 0x0e8acA05A8B35516504690Fa97fAEa69bbAFf901

**Comment by Navidda** [comment]
I guess this is also related.
https://github.com/rwth-acis/mobsos-surveys/issues/32#issuecomment-891993613

**Comment by Aran30** [comment]
Cause of problem: 
Have a running instance of an ethereum node, login in the frontend via learning layers -> user created, stored in DHT, pubkey+username stored in blockchain. 

Problem: 
Delete/Badly configure node storage such that user envelope is lost and then re-created upon new login. This leads to a new public/private key pair, where the public key is different from the one stored in the blockchain. 

Possible Solutions: 
1. reset the blockchain data (worst case scenario)
2. upon logging in in the frontend, using the agent tool export your own's agent xml file. In case the node storage is corrupt, delete it and upload your xml file to the network
